# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\ndozer.auth\",\n\x13GetAuthTokenRequest\x12\x15\n\raccess_filter\x18\x01 \x01(\t\"%\n\x14GetAuthTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t2d\n\x0f\x41uthGrpcService\x12Q\n\x0cgetAuthToken\x12\x1f.dozer.auth.GetAuthTokenRequest\x1a .dozer.auth.GetAuthTokenResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETAUTHTOKENREQUEST._serialized_start=26
  _GETAUTHTOKENREQUEST._serialized_end=70
  _GETAUTHTOKENRESPONSE._serialized_start=72
  _GETAUTHTOKENRESPONSE._serialized_end=109
  _AUTHGRPCSERVICE._serialized_start=111
  _AUTHGRPCSERVICE._serialized_end=211
# @@protoc_insertion_point(module_scope)
