# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x0c\x64ozer.health\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa7\x01\n\x13HealthCheckResponse\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.dozer.health.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32\xbd\x01\n\x11HealthGrpcService\x12R\n\x0bhealthCheck\x12 .dozer.health.HealthCheckRequest\x1a!.dozer.health.HealthCheckResponse\x12T\n\x0bhealthWatch\x12 .dozer.health.HealthCheckRequest\x1a!.dozer.health.HealthCheckResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEALTHCHECKREQUEST._serialized_start=30
  _HEALTHCHECKREQUEST._serialized_end=67
  _HEALTHCHECKRESPONSE._serialized_start=70
  _HEALTHCHECKRESPONSE._serialized_end=237
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_start=158
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_end=237
  _HEALTHGRPCSERVICE._serialized_start=240
  _HEALTHGRPCSERVICE._serialized_end=429
# @@protoc_insertion_point(module_scope)
