# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pydozer.types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cingest.proto\x12\x0c\x64ozer.ingest\x1a\x0btypes.proto\"\x9f\x01\n\rIngestRequest\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\'\n\x03typ\x18\x02 \x01(\x0e\x32\x1a.dozer.types.OperationType\x12\x1f\n\x03old\x18\x03 \x03(\x0b\x32\x12.dozer.types.Value\x12\x1f\n\x03new\x18\x04 \x03(\x0b\x32\x12.dozer.types.Value\x12\x0e\n\x06seq_no\x18\x05 \x01(\r\" \n\x0eIngestResponse\x12\x0e\n\x06seq_no\x18\x01 \x01(\r\"\xdb\x01\n\x12IngestArrowRequest\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\x0f\n\x07records\x18\x02 \x01(\x0c\x12\x0e\n\x06seq_no\x18\x03 \x01(\r\x12@\n\x08metadata\x18\x04 \x03(\x0b\x32..dozer.ingest.IngestArrowRequest.MetadataEntry\x1aM\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.dozer.ingest.IngestMetadata:\x02\x38\x01\"K\n\x0eIngestMetadata\x12(\n\x03typ\x18\x01 \x01(\x0e\x32\x1b.dozer.ingest.OperationType\x12\x0f\n\x07version\x18\x02 \x01(\r*3\n\rOperationType\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x32\xcb\x02\n\rIngestService\x12\x43\n\x06ingest\x12\x1b.dozer.ingest.IngestRequest\x1a\x1c.dozer.ingest.IngestResponse\x12L\n\ringest_stream\x12\x1b.dozer.ingest.IngestRequest\x1a\x1c.dozer.ingest.IngestResponse(\x01\x12N\n\x0cingest_arrow\x12 .dozer.ingest.IngestArrowRequest\x1a\x1c.dozer.ingest.IngestResponse\x12W\n\x13ingest_arrow_stream\x12 .dozer.ingest.IngestArrowRequest\x1a\x1c.dozer.ingest.IngestResponse(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INGESTARROWREQUEST_METADATAENTRY._options = None
  _INGESTARROWREQUEST_METADATAENTRY._serialized_options = b'8\001'
  _OPERATIONTYPE._serialized_start=538
  _OPERATIONTYPE._serialized_end=589
  _INGESTREQUEST._serialized_start=44
  _INGESTREQUEST._serialized_end=203
  _INGESTRESPONSE._serialized_start=205
  _INGESTRESPONSE._serialized_end=237
  _INGESTARROWREQUEST._serialized_start=240
  _INGESTARROWREQUEST._serialized_end=459
  _INGESTARROWREQUEST_METADATAENTRY._serialized_start=382
  _INGESTARROWREQUEST_METADATAENTRY._serialized_end=459
  _INGESTMETADATA._serialized_start=461
  _INGESTMETADATA._serialized_end=536
  _INGESTSERVICE._serialized_start=592
  _INGESTSERVICE._serialized_end=923
# @@protoc_insertion_point(module_scope)
